services:
  aspire-dashboard:
    stdin_open: true
    tty: true
    ports:
      - 18888:18888
      - 4317:18889
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest